<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">

# Introduction to APIs

## The `requests` Library
The `requests` library is a library for submitting HTTP requests from Python. Despite its frequent use, it's not included in the Python standard library. You'll need to `pip install requests` yourself.
![](imgs/pokeapi.png)

In [1]:
import requests

In [2]:
# Create url for API call.

In [3]:
# Make request

In [5]:
# Request response code

200

In [1]:
# Text of request

In [11]:
# Bring in the JSON!

dict

In [12]:
# Since we've converted the JSON -> dict, we know how to work with this!

dict_keys(['abilities', 'base_experience', 'forms', 'game_indices', 'height', 'held_items', 'id', 'is_default', 'location_area_encounters', 'moves', 'name', 'order', 'species', 'sprites', 'stats', 'types', 'weight'])

In [32]:
# Height, Weight

5
90

In [30]:
# Sprites?

{'back_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/7.png',
 'back_female': None,
 'back_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/7.png',
 'back_shiny_female': None,
 'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png',
 'front_female': None,
 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/7.png',
 'front_shiny_female': None}

In [34]:
# What moves can squirtle learn?

[{'move': {'name': 'mega-punch', 'url': 'https://pokeapi.co/api/v2/move/5/'},
  'version_group_details': [{'level_learned_at': 0,
    'move_learn_method': {'name': 'machine',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
    'version_group': {'name': 'red-blue',
     'url': 'https://pokeapi.co/api/v2/version-group/1/'}},
   {'level_learned_at': 0,
    'move_learn_method': {'name': 'machine',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
    'version_group': {'name': 'yellow',
     'url': 'https://pokeapi.co/api/v2/version-group/2/'}},
   {'level_learned_at': 0,
    'move_learn_method': {'name': 'tutor',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
    'version_group': {'name': 'emerald',
     'url': 'https://pokeapi.co/api/v2/version-group/6/'}},
   {'level_learned_at': 0,
    'move_learn_method': {'name': 'tutor',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
    'version_group': {'name': 'firered-leafgreen',
     'url': 'https://pokeapi.co/api/v2/version-group/7/'}}]},
 {'move': {'name': 'ice-punch', 'url': 'https://pokeapi.co/api/v2/move/8/'},
  'version_group_details': [{'level_learned_at': 0,
    'move_learn_method': {'name': 'machine',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
    'version_group': {'name': 'gold-silver',
     'url': 'https://pokeapi.co/api/v2/version-group/3/'}},
   {'level_learned_at': 0,
    'move_learn_method': {'name': 'machine',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
    'version_group': {'name': 'crystal',
     'url': 'https://pokeapi.co/api/v2/version-group/4/'}},
   {'level_learned_at': 0,
    'move_learn_method': {'name': 'tutor',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
    'version_group': {'name': 'emerald',
     'url': 'https://pokeapi.co/api/v2/version-group/6/'}},
   {'level_learned_at': 0,
    'move_learn_method': {'name': 'tutor',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
    'version_group': {'name': 'platinum',
     'url': 'https://pokeapi.co/api/v2/version-group/9/'}},
   {'level_learned_at': 0,
    'move_learn_method': {'name': 'tutor',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
    'version_group': {'name': 'heartgold-soulsilver',
     'url': 'https://pokeapi.co/api/v2/version-group/10/'}},
   {'level_learned_at': 0,
    'move_learn_method': {'name': 'tutor',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
    'version_group': {'name': 'black-2-white-2',
     'url': 'https://pokeapi.co/api/v2/version-group/14/'}},
   {'level_learned_at': 0,
    'move_learn_method': {'name': 'tutor',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
    'version_group': {'name': 'omega-ruby-alpha-sapphire',
     'url': 'https://pokeapi.co/api/v2/version-group/16/'}}]},
 {'move': {'name': 'mega-kick', 'url': 'https://pokeapi.co/api/v2/move/25/'},
  'version_group_details': [{'level_learned_at': 0,
    'move_learn_method': {'name': 'machine',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
    'version_group': {'name': 'red-blue',
     'url': 'https://pokeapi.co/api/v2/version-group/1/'}},
   {'level_learned_at': 0,
    'move_learn_method': {'name': 'machine',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
    'version_group': {'name': 'yellow',
     'url': 'https://pokeapi.co/api/v2/version-group/2/'}},
   {'level_learned_at': 0,
    'move_learn_method': {'name': 'tutor',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
    'version_group': {'name': 'emerald',
     'url': 'https://pokeapi.co/api/v2/version-group/6/'}},
   {'level_learned_at': 0,
    'move_learn_method': {'name': 'tutor',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
    'version_group': {'name': 'firered-leafgreen',
     'url': 'https://pokeapi.co/api/v2/version-group/7/'}}]},
 {'move': {'name': 'headbutt', 'url': 'https://pokeapi.co/api/v2/move/29/'},
  'version_group_details': [{'level_learned_at': 0,
    'move_learn_method': {'name': 'machine',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
    'version_group': {'name': 'crystal',
     'url': 'https://pokeapi.co/api/v2/version-group/4/'}},
   {'level_learned_at': 0,
    'move_learn_method': {'name': 'machine',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
    'version_group': {'name': 'gold-silver',
     'url': 'https://pokeapi.co/api/v2/version-group/3/'}},
   {'level_learned_at': 0,
    'move_learn_method': {'name': 'tutor',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
    'version_group': {'name': 'heartgold-soulsilver',
     'url': 'https://pokeapi.co/api/v2/version-group/10/'}}]},
 {'move': {'name': 'tackle', 'url': 'https://pokeapi.co/api/v2/move/33/'},
  'version_group_details': [{'level_learned_at': 1,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'ultra-sun-ultra-moon',
     'url': 'https://pokeapi.co/api/v2/version-group/18/'}},
   {'level_learned_at': 1,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'sun-moon',
     'url': 'https://pokeapi.co/api/v2/version-group/17/'}},
   {'level_learned_at': 1,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'omega-ruby-alpha-sapphire',
     'url': 'https://pokeapi.co/api/v2/version-group/16/'}},
   {'level_learned_at': 1,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'black-2-white-2',
     'url': 'https://pokeapi.co/api/v2/version-group/14/'}},
   {'level_learned_at': 1,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'xd',
     'url': 'https://pokeapi.co/api/v2/version-group/13/'}},
   {'level_learned_at': 1,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'colosseum',
     'url': 'https://pokeapi.co/api/v2/version-group/12/'}},
   {'level_learned_at': 1,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'black-white',
     'url': 'https://pokeapi.co/api/v2/version-group/11/'}},
   {'level_learned_at': 1,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'firered-leafgreen',
     'url': 'https://pokeapi.co/api/v2/version-group/7/'}},
   {'level_learned_at': 1,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'x-y',
     'url': 'https://pokeapi.co/api/v2/version-group/15/'}},
   {'level_learned_at': 1,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'emerald',
     'url': 'https://pokeapi.co/api/v2/version-group/6/'}},
   {'level_learned_at': 1,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'ruby-sapphire',
     'url': 'https://pokeapi.co/api/v2/version-group/5/'}},
   {'level_learned_at': 1,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'crystal',
     'url': 'https://pokeapi.co/api/v2/version-group/4/'}},
   {'level_learned_at': 1,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'gold-silver',
     'url': 'https://pokeapi.co/api/v2/version-group/3/'}},
   {'level_learned_at': 1,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'heartgold-soulsilver',
     'url': 'https://pokeapi.co/api/v2/version-group/10/'}},
   {'level_learned_at': 1,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'platinum',
     'url': 'https://pokeapi.co/api/v2/version-group/9/'}},
   {'level_learned_at': 1,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'diamond-pearl',
     'url': 'https://pokeapi.co/api/v2/version-group/8/'}},
   {'level_learned_at': 1,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'yellow',
     'url': 'https://pokeapi.co/api/v2/version-group/2/'}},
   {'level_learned_at': 1,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'red-blue',
     'url': 'https://pokeapi.co/api/v2/version-group/1/'}}]},
 {'move': {'name': 'body-slam', 'url': 'https://pokeapi.co/api/v2/move/34/'},
  'version_group_details': [{'level_learned_at': 0,
    'move_learn_method': {'name': 'tutor',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
    'version_group': {'name': 'xd',
     'url': 'https://pokeapi.co/api/v2/version-group/13/'}},
   {'level_learned_at': 0,
    'move_learn_method': {'name': 'tutor',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
    'version_group': {'name': 'firered-leafgreen',
     'url': 'https://pokeapi.co/api/v2/version-group/7/'}},
   {'level_learned_at': 0,
    'move_learn_method': {'name': 'tutor',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
    'version_group': {'name': 'emerald',
     'url': 'https://pokeapi.co/api/v2/version-group/6/'}},
   {'level_learned_at': 0,
    'move_learn_method': {'name': 'machine',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
    'version_group': {'name': 'yellow',
     'url': 'https://pokeapi.co/api/v2/version-group/2/'}},
   {'level_learned_at': 0,
    'move_learn_method': {'name': 'machine',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
    'version_group': {'name': 'red-blue',
     'url': 'https://pokeapi.co/api/v2/version-group/1/'}}]},
 {'move': {'name': 'take-down', 'url': 'https://pokeapi.co/api/v2/move/36/'},
  'version_group_details': [{'level_learned_at': 0,
    'move_learn_method': {'name': 'machine',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
    'version_group': {'name': 'yellow',
     'url': 'https://pokeapi.co/api/v2/version-group/2/'}},
   {'level_learned_at': 0,
    'move_learn_method': {'name': 'machine',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
    'version_group': {'name': 'red-blue',
     'url': 'https://pokeapi.co/api/v2/version-group/1/'}}]},
 {'move': {'name': 'double-edge', 'url': 'https://pokeapi.co/api/v2/move/38/'},
  'version_group_details': [{'level_learned_at': 0,
    'move_learn_method': {'name': 'tutor',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
    'version_group': {'name': 'xd',
     'url': 'https://pokeapi.co/api/v2/version-group/13/'}},
   {'level_learned_at': 0,
    'move_learn_method': {'name': 'tutor',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
    'version_group': {'name': 'firered-leafgreen',
     'url': 'https://pokeapi.co/api/v2/version-group/7/'}},
   {'level_learned_at': 0,
    'move_learn_method': {'name': 'tutor',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
    'version_group': {'name': 'emerald',
     'url': 'https://pokeapi.co/api/v2/version-group/6/'}},
   {'level_learned_at': 0,
    'move_learn_method': {'name': 'machine',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
    'version_group': {'name': 'yellow',
     'url': 'https://pokeapi.co/api/v2/version-group/2/'}},
   {'level_learned_at': 0,
    'move_learn_method': {'name': 'machine',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
    'version_group': {'name': 'red-blue',
     'url': 'https://pokeapi.co/api/v2/version-group/1/'}}]},
 {'move': {'name': 'tail-whip', 'url': 'https://pokeapi.co/api/v2/move/39/'},
  'version_group_details': [{'level_learned_at': 1,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'red-blue',
     'url': 'https://pokeapi.co/api/v2/version-group/1/'}},
   {'level_learned_at': 1,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'yellow',
     'url': 'https://pokeapi.co/api/v2/version-group/2/'}},
   {'level_learned_at': 4,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'gold-silver',
     'url': 'https://pokeapi.co/api/v2/version-group/3/'}},
   {'level_learned_at': 4,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'crystal',
     'url': 'https://pokeapi.co/api/v2/version-group/4/'}},
   {'level_learned_at': 4,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'ruby-sapphire',
     'url': 'https://pokeapi.co/api/v2/version-group/5/'}},
   {'level_learned_at': 4,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'emerald',
     'url': 'https://pokeapi.co/api/v2/version-group/6/'}},
   {'level_learned_at': 4,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'firered-leafgreen',
     'url': 'https://pokeapi.co/api/v2/version-group/7/'}},
   {'level_learned_at': 4,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'diamond-pearl',
     'url': 'https://pokeapi.co/api/v2/version-group/8/'}},
   {'level_learned_at': 4,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'platinum',
     'url': 'https://pokeapi.co/api/v2/version-group/9/'}},
   {'level_learned_at': 4,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'heartgold-soulsilver',
     'url': 'https://pokeapi.co/api/v2/version-group/10/'}},
   {'level_learned_at': 4,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'black-white',
     'url': 'https://pokeapi.co/api/v2/version-group/11/'}},
   {'level_learned_at': 4,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'colosseum',
     'url': 'https://pokeapi.co/api/v2/version-group/12/'}},
   {'level_learned_at': 4,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'xd',
     'url': 'https://pokeapi.co/api/v2/version-group/13/'}},
   {'level_learned_at': 4,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'black-2-white-2',
     'url': 'https://pokeapi.co/api/v2/version-group/14/'}},
   {'level_learned_at': 4,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'x-y',
     'url': 'https://pokeapi.co/api/v2/version-group/15/'}},
   {'level_learned_at': 4,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'omega-ruby-alpha-sapphire',
     'url': 'https://pokeapi.co/api/v2/version-group/16/'}},
   {'level_learned_at': 4,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'sun-moon',
     'url': 'https://pokeapi.co/api/v2/version-group/17/'}},
   {'level_learned_at': 4,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'ultra-sun-ultra-moon',
     'url': 'https://pokeapi.co/api/v2/version-group/18/'}}]},
 {'move': {'name': 'bite', 'url': 'https://pokeapi.co/api/v2/move/44/'},
  'version_group_details': [{'level_learned_at': 16,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'ultra-sun-ultra-moon',
     'url': 'https://pokeapi.co/api/v2/version-group/18/'}},
   {'level_learned_at': 16,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'sun-moon',
     'url': 'https://pokeapi.co/api/v2/version-group/17/'}},
   {'level_learned_at': 16,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'omega-ruby-alpha-sapphire',
     'url': 'https://pokeapi.co/api/v2/version-group/16/'}},
   {'level_learned_at': 16,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'black-2-white-2',
     'url': 'https://pokeapi.co/api/v2/version-group/14/'}},
   {'level_learned_at': 18,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'xd',
     'url': 'https://pokeapi.co/api/v2/version-group/13/'}},
   {'level_learned_at': 18,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'colosseum',
     'url': 'https://pokeapi.co/api/v2/version-group/12/'}},
   {'level_learned_at': 16,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'black-white',
     'url': 'https://pokeapi.co/api/v2/version-group/11/'}},
   {'level_learned_at': 18,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'firered-leafgreen',
     'url': 'https://pokeapi.co/api/v2/version-group/7/'}},
   {'level_learned_at': 16,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'x-y',
     'url': 'https://pokeapi.co/api/v2/version-group/15/'}},
   {'level_learned_at': 18,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'emerald',
     'url': 'https://pokeapi.co/api/v2/version-group/6/'}},
   {'level_learned_at': 18,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'ruby-sapphire',
     'url': 'https://pokeapi.co/api/v2/version-group/5/'}},
   {'level_learned_at': 18,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'crystal',
     'url': 'https://pokeapi.co/api/v2/version-group/4/'}},
   {'level_learned_at': 18,
    'move_learn_method': {'name': 'level-up',
     'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
    'version_group': {'name': 'gold-silver',

In [45]:
# Whoa! Let's build a function to extract a pokemon's possible moves

## Ok, let's try a more complicated API - for stocks!
![](imgs/alpha-vantage.png)
If you haven't already - grab your free API key for Alpha Vantage [here](https://www.alphavantage.co). It takes five seconds.

**(THREAD): Why do you think companies would require the use of an API key?**

Alpha Vantage has documentation [here](https://www.alphavantage.co/documentation/).

In [48]:
# Most APIs have a single base URL from which API calls are made.
# If you look closely at the examples, this is Alpha Vantage's.
base_url = "https://www.alphavantage.co/query"

In [49]:
# Let's build out this request.
# This is a very common format for pure API requests to come in

In [53]:
# Let's grab that data!

In [57]:
# Well, this looks like a familiar format...

             1. open   2. high    3. low  4. close 5. volume
2019-06-24  198.5400  200.1600  198.1700  199.0929  12130567
2019-06-21  198.8000  200.8500  198.1500  198.7800  47800589
2019-06-20  200.3700  200.6100  198.0300  199.4600  21513988
2019-06-19  199.6800  199.8800  197.3100  197.8700  21124235
2019-06-18  196.0500  200.2900  195.2100  198.4500  26551004

### Challenge
Write your own function that inputs a ticker symbol and outputs the above.

             1. open   2. high    3. low  4. close 5. volume
2019-06-24  198.5400  200.1600  198.1700  198.9267  12398351
2019-06-21  198.8000  200.8500  198.1500  198.7800  47800589
2019-06-20  200.3700  200.6100  198.0300  199.4600  21513988
2019-06-19  199.6800  199.8800  197.3100  197.8700  21124235
2019-06-18  196.0500  200.2900  195.2100  198.4500  26551004

### Did this feel like a lot of work? You're not alone.
For web APIs such as these, open sourcerers (ordinary programmers like you and me!) like to build language-specific **API wrappers** to easier call the API. Interestingly, based on our very vague definition of APIs, API wrappers are also themselves APIs!

Alpha Vantage has a Python API wrapper made by user `RomelTorres` [here](https://github.com/RomelTorres/alpha_vantage)!

![](imgs/opensource.jpg)

## You want data? You got data.

### Key Takeaway #1: Your favorite thing has a free API
* **Stock prices**: [Alpha Vantage](https://github.com/RomelTorres/alpha_vantage)
* **Cryptocurrency prices**: [ccxt](https://github.com/ccxt/ccxt) provides a unified API for several cryptocurrency markets. You can even buy and sell crypto from within Python!
* **Weather**: [OpenWeather](https://openweathermap.org/api)

### Key Takeaway #2: Your favorite website has a free API
Below is a brief list of websites that have a free API. Note that "free" here means "zero-cost", not "permissive and easy to use." APIs can be abused. Not all Twitter bots are friendly like [Every Sheriff Bot](https://twitter.com/EverySheriff).
* Twitter
* Reddit
* Yelp
* Twitch
* Facebook/Instagram
* GitHub (yes, even GitHub!)
* Most Google services
* Spotify
* Slack (no, you can't have a key.)

## Conclusion & Summary
Today we asked for data **nicely** using APIs. Next week we'll use our battering ram, **Beautiful Soup** to do some webscraping.

Today, we
* Learned how HTTP works and
* How we can make HTTP requests from the Python (and also the CL a little)
* How to read API documentation and get the data we want from the internet